{
 "title": "Netflow Overview",
 "time": { "from": "2020-07-09T00:00:00.000Z", "to": "2020-07-17T23:59:59.000Z" },
 "panels": [
  {
   "title": "Packets by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "ICMP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.packets", "id": "1", "type": "sum" }
     ],
     "query": "prot:1",
     "timeField": "@timestamp"
    },
    {
     "alias": "TCP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.packets", "id": "1", "type": "sum" }
     ],
     "query": "prot:6",
     "timeField": "@timestamp"
    },
    {
     "alias": "UDP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.packets", "id": "1", "type": "sum" }
     ],
     "query": "prot:17",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Navigation",
   "type": "dashlist",
   "gridPos": { "h": 22, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "alias": "Traffic summary",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic by protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ICMP",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "source.bytes",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "prot:1",
     "timeField": "@timestamp"
    },
    {
     "alias": "TCP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "query": "prot:6",
     "timeField": "@timestamp"
    },
    {
     "alias": "UDP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "query": "prot:17",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Netflow records count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top20 Src",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Packets & Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Packets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.packets", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top20 Dst",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top20 Src Port",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.port",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top20 Dst Port",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.port",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}